services:
  SaaSFormation\Framework\MySQLBasedWriteModel\Infrastructure\WriteModel\MySQLClientProvider:
    public: true
    arguments:
      $envVarsManager: '@default_env_vars_manager'

  SaaSFormation\Framework\MySQLBasedWriteModel\Infrastructure\WriteModel\MySQLBasedRepository:
    arguments:
      $mySQLClientProvider: '@SaaSFormation\Framework\MySQLBasedWriteModel\Infrastructure\WriteModel\MySQLClientProvider'
      $logger: '@default_logger'
      $uuidFactory: '@SaaSFormation\Framework\Contracts\Common\Identity\UUIDFactoryInterface'

  SaaSFormation\Framework\Contracts\Infrastructure\WriteModel\ClientProviderInterface:
    alias: 'SaaSFormation\Framework\MySQLBasedWriteModel\Infrastructure\WriteModel\MySQLClientProvider'
    public: true
  SaaSFormation\Framework\Contracts\Domain\WriteModel\RepositoryInterface: '@SaaSFormation\Framework\MySQLBasedWriteModel\Infrastructure\WriteModel\MySQLBasedRepository'