services:
  SaaSFormation\Framework\MySQLBasedWriteModel\Infrastructure\WriteModel\MySQLClientProvider:
    public: true
    arguments:
      $envVarsManager: '@default_env_vars_manager'
      $logger: '@default_logger'

  SaaSFormation\Framework\MySQLBasedWriteModel\Infrastructure\WriteModel\MySQLBasedRepository:
    arguments:
      $mySQLClientProvider: '@SaaSFormation\Framework\MySQLBasedWriteModel\Infrastructure\WriteModel\MySQLClientProvider'

  SaaSFormation\Framework\Contracts\Infrastructure\WriteModel\ClientProviderInterface:
    alias: 'SaaSFormation\Framework\MySQLBasedWriteModel\Infrastructure\WriteModel\MySQLClientProvider'
    public: true

  SaaSFormation\Framework\MySQLBasedWriteModel\Infrastructure\WriteModel\MySQLMigrationsRepository:
    arguments:
      $mySQLClientProvider: '@SaaSFormation\Framework\MySQLBasedWriteModel\Infrastructure\WriteModel\MySQLClientProvider'

  SaaSFormation\Framework\MySQLBasedWriteModel\UI\Cli\Migrations\MigrateCommand:
    public: true

  SaaSFormation\Framework\SharedKernel\Domain\WriteModel\RepositoryInterface: '@SaaSFormation\Framework\MySQLBasedWriteModel\Infrastructure\WriteModel\MySQLBasedRepository'