services:
  SaaSFormation\Framework\Projects\Infrastructure\MySQLClientProvider:
    public: true
    arguments:
      $envVarsManager: '@default_env_vars_manager'

  SaaSFormation\Framework\Projects\Infrastructure\MySQLBasedWriteModelRepository:
    arguments:
      $mySQLClientProvider: '@SaaSFormation\Framework\Projects\Infrastructure\MySQLClientProvider'
      $logger: '@default_logger'
      $uuidFactory: '@SaaSFormation\Framework\Contracts\Common\Identity\UUIDFactoryInterface'